-- AlterTable
ALTER TABLE `contrato` MODIFY `pec` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `grupoCliente` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `empresa` VARCHAR(1200) NOT NULL DEFAULT '',
    MODIFY `docSolid` VARCHAR(1200) NULL DEFAULT '',
    MODIFY `mesReajuste` VARCHAR(191) NOT NULL DEFAULT '';
