-- AlterTable
ALTER TABLE `CONTRATO` ADD COLUMN `idReajusteComparar1` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `idReajusteComparar2` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `idReajusteComparar3` INTEGER NOT NULL DEFAULT 0;
