-- DropForeignKey
ALTER TABLE `CR_CONTRATO` DROP FOREIGN KEY `CR_CONTRATO_numContratoId_fkey`;

-- AlterTable
ALTER TABLE `CR_CONTRATO` ADD COLUMN `valorCr` DECIMAL(11, 2) NULL,
    MODIFY `numContratoId` VARCHAR(191) NOT NULL;

-- AddForeignKey
ALTER TABLE `CR_CONTRATO` ADD CONSTRAINT `CR_CONTRATO_numContratoId_fkey` FOREIGN KEY (`numContratoId`) REFERENCES `CONTRATO`(`documento`) ON DELETE RESTRICT ON UPDATE CASCADE;
